export type CityStyleCategory = 'building' | 'environment' | 'street';
export type ModelScaleAxis = 'height' | 'horizontal' | 'longest';
export type ModelAnimation = 'cloud' | 'fire' | 'water';

export interface CityStyleModel {
  id: string;
  label: string;
  category: CityStyleCategory;
  role: string;
  featured: boolean;
  modelPath: string;
  sourceUrl: string;
  licenseName: 'Three.js Assets Free Commercial License';
  licenseUrl: string;
  targetSizeMetres: number;
  scaleAxis: ModelScaleAxis;
  position: readonly [number, number, number];
  rotationY: number;
  animation?: ModelAnimation;
}

export const MODEL_CATEGORY_LABELS: Readonly<Record<CityStyleCategory, string>> = {
  building: '建築與店舖',
  environment: '自然環境',
  street: '街道設施',
};

const license = {
  licenseName: 'Three.js Assets Free Commercial License',
  licenseUrl: 'https://threejsassets.com/license#free-asset-license',
} as const;

export const CITY_STYLE_MODELS = [
  {
    id: 'apartment-block-01',
    label: 'Apartment Block 01',
    category: 'building',
    role: '舊區中低層住宅',
    featured: true,
    modelPath: '/models/city-style/buildings/apartment-block-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/apartment-block-01',
    targetSizeMetres: 28,
    scaleAxis: 'height',
    position: [-27, 0, -10],
    rotationY: 0.16,
    ...license,
  },
  {
    id: 'glass-skyscraper-01',
    label: 'Glass Skyscraper 01',
    category: 'building',
    role: '商業核心高樓',
    featured: true,
    modelPath: '/models/city-style/buildings/glass-skyscraper-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/glass-skyscraper-01',
    targetSizeMetres: 88,
    scaleAxis: 'height',
    position: [4, 0, -20],
    rotationY: -0.22,
    ...license,
  },
  {
    id: 'convenience-store-01',
    label: 'Convenience Store 01',
    category: 'building',
    role: '街角零售地標',
    featured: true,
    modelPath: '/models/city-style/buildings/convenience-store-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/convenience-store-01',
    targetSizeMetres: 7,
    scaleAxis: 'height',
    position: [30, 0, 8],
    rotationY: -0.38,
    ...license,
  },
  {
    id: 'corner-store-01',
    label: 'Corner Store 01',
    category: 'building',
    role: '社區轉角店',
    featured: false,
    modelPath: '/models/city-style/buildings/corner-store-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/corner-store-01',
    targetSizeMetres: 9,
    scaleAxis: 'height',
    position: [43, 0, -8],
    rotationY: -0.45,
    ...license,
  },
  {
    id: 'home-thatched-house-01',
    label: 'Thatched House 01',
    category: 'building',
    role: '村落工作小屋',
    featured: false,
    modelPath: '/models/city-style/buildings/home-thatched-house-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/home-thatched-house-01',
    targetSizeMetres: 8,
    scaleAxis: 'height',
    position: [-44, 0, 18],
    rotationY: 0.36,
    ...license,
  },
  {
    id: 'shop-awning-01',
    label: 'Shop Awning 01',
    category: 'building',
    role: '店面遮篷',
    featured: false,
    modelPath: '/models/city-style/buildings/shop-awning-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/shop-awning-01',
    targetSizeMetres: 6,
    scaleAxis: 'horizontal',
    position: [30, 0, 13],
    rotationY: -0.38,
    ...license,
  },
  {
    id: 'terrain-grass-01',
    label: 'Terrain Grass 01',
    category: 'environment',
    role: '村落草地基座',
    featured: false,
    modelPath: '/models/city-style/environment/terrain-grass-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/terrain-grass-01',
    targetSizeMetres: 36,
    scaleAxis: 'horizontal',
    position: [-42, -0.1, 20],
    rotationY: 0.12,
    ...license,
  },
  {
    id: 'water-open-oasis',
    label: 'Water Open Oasis',
    category: 'environment',
    role: '開放水景',
    featured: false,
    modelPath: '/models/city-style/environment/water-open-oasis.glb',
    sourceUrl: 'https://threejsassets.com/assets/water-open-oasis',
    targetSizeMetres: 18,
    scaleAxis: 'horizontal',
    position: [50, 0, 33],
    rotationY: 0.1,
    animation: 'water',
    ...license,
  },
  {
    id: 'tree-oak-01',
    label: 'Tree Oak 01',
    category: 'environment',
    role: '廣場遮蔭樹',
    featured: false,
    modelPath: '/models/city-style/environment/tree-oak-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/tree-oak-01',
    targetSizeMetres: 13,
    scaleAxis: 'height',
    position: [-53, 0, 6],
    rotationY: -0.42,
    ...license,
  },
  {
    id: 'date-palm',
    label: 'Date Palm',
    category: 'environment',
    role: '水邊高樹',
    featured: false,
    modelPath: '/models/city-style/environment/date-palm.glb',
    sourceUrl: 'https://threejsassets.com/assets/date-palm',
    targetSizeMetres: 11,
    scaleAxis: 'height',
    position: [48, 0, 16],
    rotationY: 0.2,
    ...license,
  },
  {
    id: 'bush-round-01',
    label: 'Bush Round 01',
    category: 'environment',
    role: '店前綠化',
    featured: false,
    modelPath: '/models/city-style/environment/bush-round-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/bush-round-01',
    targetSizeMetres: 1.8,
    scaleAxis: 'height',
    position: [24, 0, 7],
    rotationY: 0.4,
    ...license,
  },
  {
    id: 'cloud-puff-01',
    label: 'Cloud Puff 01',
    category: 'environment',
    role: '天空層次',
    featured: false,
    modelPath: '/models/city-style/environment/cloud-puff-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/cloud-puff-01',
    targetSizeMetres: 24,
    scaleAxis: 'longest',
    position: [20, 73, -45],
    rotationY: 0.1,
    animation: 'cloud',
    ...license,
  },
  {
    id: 'road-cobble-straight-01',
    label: 'Road Cobble Straight 01',
    category: 'street',
    role: '街區主路',
    featured: false,
    modelPath: '/models/city-style/street/road-cobble-straight-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/road-cobble-straight-01',
    targetSizeMetres: 48,
    scaleAxis: 'horizontal',
    position: [-18, 0.02, 25],
    rotationY: 0.08,
    ...license,
  },
  {
    id: 'bench-01',
    label: 'Bench 01',
    category: 'street',
    role: '公共休憩點',
    featured: false,
    modelPath: '/models/city-style/street/bench-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/bench-01',
    targetSizeMetres: 3.6,
    scaleAxis: 'horizontal',
    position: [-5, 0, 18],
    rotationY: 0.08,
    ...license,
  },
  {
    id: 'trash-bin-01',
    label: 'Trash Bin 01',
    category: 'street',
    role: '街道清潔設施',
    featured: false,
    modelPath: '/models/city-style/street/trash-bin-01.glb',
    sourceUrl: 'https://threejsassets.com/assets/trash-bin-01',
    targetSizeMetres: 1.35,
    scaleAxis: 'height',
    position: [0, 0, 18],
    rotationY: 0.08,
    ...license,
  },
  {
    id: 'fire-brazier',
    label: 'Fire Brazier',
    category: 'street',
    role: '夜間暖光焦點',
    featured: false,
    modelPath: '/models/city-style/street/fire-brazier.glb',
    sourceUrl: 'https://threejsassets.com/assets/fire-brazier',
    targetSizeMetres: 1.5,
    scaleAxis: 'height',
    position: [-14, 0, 18],
    rotationY: 0,
    animation: 'fire',
    ...license,
  },
] as const satisfies readonly CityStyleModel[];
